version: "3.5"

networks:
  minio-network:
    driver: bridge

services:
  minio:
    image: "bitnami/minio:latest"
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
    networks:
      - minio-network
